name: akmal_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  easy_sticky_header: ^1.0.5
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  get: 4.6.5
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
